---
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcoffin/armake2:2e66c92
    steps:
      - uses: actions/checkout@v4

      - name: Write secret file to disk
        env:
          DIS_BIPRIVATEKEY_B64: ${{ secrets.DIS_BIPRIVATEKEY_B64 }}
        run: |
          echo "$DIS_BIPRIVATEKEY_B64" | base64 -d > /tmp/dis.biprivatekey

      - name: Build the mod folder
        run: ./build_mod.sh /tmp/dis.biprivatekey

      - name: Upload mod as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "@DIS-Exporter"
          path: "@DIS-Exporter/"
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    container: steamcmd/steamcmd:alpine-3
    needs: build
    steps:
      - name: Download built mod artifact
        uses: actions/download-artifact@v4
        with:
          name: "@DIS-Exporter"
      - name: List files in mod folder
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: >
          steamcmd
          "+login ${STEAM_USERNAME} ${STEAM_PASSWORD}"
          "+exit"
